global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'headscale-prod'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'

  # Headscale metrics
  - job_name: 'headscale'
    static_configs:
      - targets: ['headscale:9090']
    metrics_path: '/metrics'

  # Orchestrator API metrics
  - job_name: 'orchestrator-api'
    static_configs:
      - targets: ['api-orchestrator:8000']
    metrics_path: '/metrics'

  # PostgreSQL metrics (via postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']

  # Node metrics (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'

  # DERP server metrics
  - job_name: 'derp'
    static_configs:
      - targets: ['derper:8030']
    metrics_path: '/debug/vars'