global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@tailnet.work'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  # routes:
  # - match:
  #     severity: critical
  #   receiver: 'critical-alerts'
  # - match:
  #     severity: warning
  #   receiver: 'warning-alerts'

receivers:
- name: 'default-receiver'
  # Default receiver - no webhook for now to avoid configuration errors
  # webhook_configs:
  # - url: 'http://127.0.0.1:5001/'

# - name: 'critical-alerts'
#   email_configs:
#   - to: 'admin@tailnet.work'
#     headers:
#       subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
#     body: |
#       {{ range .Alerts }}
#       Alert: {{ .Annotations.summary }}
#       Description: {{ .Annotations.description }}
#       {{ end }}
#   # slack_configs:
#   # - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#   #   channel: '#alerts'
#   #   title: 'CRITICAL Alert'
#   #   text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

# - name: 'warning-alerts'
#   email_configs:
#   - to: 'ops@tailnet.work'
#     headers:
#       subject: 'WARNING: {{ .GroupLabels.alertname }}'
#     body: |
#       {{ range .Alerts }}
#       Alert: {{ .Annotations.summary }}
#       Description: {{ .Annotations.description }}
#       {{ end }}

# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']